keys:
  - &jagd age1525sjhkw5xg77gkt5aa5d7znmllggza3dts86et0p9ur9385dssq0n2jr5
  - &basil age147jphxv0rm4qqsscusaw4glhyyvm9s0jvq22g5ksp8d8xrr7j5msczvu6u

creation_rules:
  - path_regex: hosts/basil/secrets\.ya?ml$
    key_groups:
      - age:
          - *jagd
          - *basil
